### ISSUE TITLE
restart的疑问

### ISSUE THREAD

**Issue by limingxinleo** [swoft-cloud/swoft-component#123]
偶尔出现，restart项目的时候stop会卡住，然后中断指令，就会发现主进程退出了，但是子进程就像一个个孤儿一样，没人管了

**Comment by xiangjihan** [comment]
可能还是posix有问题，关于stop的问题已经提交PR了。
#134

**Comment by limingxinleo** [comment]
@xiangjihan 我看到了。。。

**Comment by xiangjihan** [comment]
@limingxinleo 你可试一下，把restart中的posix换成swoole_process，看看能不能解决问题
