### ISSUE TITLE
[注意] Issue 请前往 swoft 项目提交 (Issue please go to the swoft project submission)

### ISSUE THREAD

**Issue by huangzhhui** [swoft-cloud/swoft-component#171]
## 注意

此仓库是开发组使用的，只接受PR(_Pull Request_)。

需要提Issue的请转到 [swoft-cloud/swoft](https://github.com/swoft-cloud/swoft/issues)

**Comment by inhere** [comment]
> English version

## attention

This repository is used by the development team and only accepts PR (_Pull Request_).

If you need to mention Issue, please go to [swoft-cloud/swoft](https://github.com/swoft-cloud/swoft/issues)
