### ISSUE TITLE
Request->json() 调用报错

### ISSUE THREAD

**Issue by ITdashu** [swoft-cloud/swoft-component#172]
> PHP Warning:  stripos() expects parameter 1 to be string, array given in /home/www-data/Project/swoft/vendor/swoft/http-message/src/Server/Concerns/InteractsWithInput.php on line 140

json方法中 stripos 调用 InteractsWithInput->getHeader 返回的数据，此方法返回数组

**Comment by huangzhhui** [comment]
请更新你的 swoft/http-message 组件
https://github.com/swoft-cloud/swoft-http-message/releases/tag/v1.0.2
