### ISSUE TITLE
服务重启不成功

### ISSUE THREAD

**Issue by jingpg** [swoft-cloud/swoft-component#243]
在生产环境运行，服务重启时偶尔不成功。经过初步排查定位为服务在停止时超时导致失败。 框架默认将超时时间设置为60秒。目前业务中有定时器任务，其执行时间超过60秒，导致停止超时。建议将服务停止时间设置为自定义，或者是将默认超时时间设定更长。

**Comment by huangzhhui** [comment]
Duplicate https://github.com/swoft-cloud/swoft/issues/461
