### ISSUE TITLE
swoft/rpc-client/src/Service/SyncServiceConnection.php  希望能够增加配置

### ISSUE THREAD

**Issue by liida** [swoft-cloud/swoft-component#331]
```

    public function recv(): string
    {
        return fread($this->connection, 1024);
    }
```
这个方法1024目前是写死的，希望能够加到配置中

**Comment by kuaileshi** [comment]
<?php
namespace Swoft\Processor;
use Dotenv\Dotenv;
use Swoft\Log\Helper\CLog;
/**
 * Env processor
 *
 * @since 2.0
 */
class EnvProcessor extends Processor
{
    /**
     * Handler env process
     *
     * @return bool
     */
    public function handle(): bool
    {
        if (!$this->application->beforeEnv()) {
            CLog::warning('Stop env processor by beforeEnv return false');
            return false;
        }
        $envFile = $this->application->getEnvFile();
        $envFile = \alias($envFile);
        $path    = \dirname($envFile);
        $env     = \basename($envFile);
        if (!\file_exists($envFile)) {
            CLog::warning('Env file(%s) is not exist! skip load it', $envFile);
            return true;
        }
        // Load env
        $dotenv = new Dotenv($path, $env);
        $dotenv->load();
        CLog::info('Env file(%s) is loaded', $envFile);
        return $this->application->afterEvent();
    }
}

配置类的后置方法afterEnv() 调用成了$this->application->afterEvent();
