### ISSUE TITLE
swoft-component/src/framework/src/Processor/EnvProcessor.php 配置后置方法定义错误

### ISSUE THREAD

**Issue by kuaileshi** [swoft-cloud/swoft-component#385]
<?php
namespace Swoft\Processor;
use Dotenv\Dotenv;
use Swoft\Log\Helper\CLog;
/**
 * Env processor
 *
 * @since 2.0
 */
class EnvProcessor extends Processor
{
    /**
     * Handler env process
     *
     * @return bool
     */
    public function handle(): bool
    {
        if (!$this->application->beforeEnv()) {
            CLog::warning('Stop env processor by beforeEnv return false');
            return false;
        }
        $envFile = $this->application->getEnvFile();
        $envFile = \alias($envFile);
        $path    = \dirname($envFile);
        $env     = \basename($envFile);
        if (!\file_exists($envFile)) {
            CLog::warning('Env file(%s) is not exist! skip load it', $envFile);
            return true;
        }
        // Load env
        $dotenv = new Dotenv($path, $env);
        $dotenv->load();
        CLog::info('Env file(%s) is loaded', $envFile);
        return $this->application->afterEvent();
    }
}
配置类的后置方法afterEnv() 调用写成了
$this->application->afterEvent();

**Comment by stelin** [comment]
@kuaileshi 谢谢返回，已修复。
