### ISSUE TITLE
task component 集成 Swoole 进程池

### ISSUE THREAD

**Issue by wujunze** [swoft-cloud/swoft-component#77]
swoft/task  component 集成 Swoole 进程池

**Comment by inhere** [comment]
估计是只用于消费任务。。。 可以这样吗

**Comment by stelin** [comment]
我们做一个使用封装，我和韩老大沟通过，没必要动态扩容。

**Comment by huangzhhui** [comment]
在这个场景没有动态伸缩是没问题，但其他的场景是有的，我去跟韩老大沟通一下

**Comment by wujunze** [comment]
JobQueue这种场景可以做成像NGINX那种模型  master worker     个人愚见 欢迎拍砖
